language: node_js
node_js:
  - lts/*
script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN
